#define PLUS                            1
#define MINUS                           2
#define DIVIDE                          3
#define TIMES                           4
#define POW                             5
#define NOT                             6
#define NEWLINE                         7
#define LP                              8
#define RP                              9
#define NUM                            10
